# Generated by Django 3.2.7 on 2021-10-31 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_expired',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
