# Generated by Django 3.2.7 on 2021-11-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_bidders_bid_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidders',
            name='bid_amount',
            field=models.FloatField(),
        ),
    ]
